# This is a basic workflow to help you get started with Actions

name: New Sentry Release and Deploy to Heroku

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
      - feature/*
  pull_request:
    branches: 
      - master
      - feature/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Create new Sentry release and deploy
        run: |
          # Install Sentry CLI
          curl -sL https://sentry.io/get-cli/ | bash

          # Create new Sentry release
          export SENTRY_RELEASE=$(sentry-cli releases propose-version)
          echo new variable created: $SENTRY_RELEASE
          sentry-cli releases -o biscuitech -p biscuitech new $SENTRY_RELEASE
          echo sentry release created
          sentry-cli releases -o biscuitech -p biscuitech set-commits --auto $SENTRY_RELEASE
          echo commits set
          sentry-cli releases -o biscuitech -p biscuitech finalize $SENTRY_RELEASE
          echo release finalized

          # Create new deploy for this Sentry release
          sentry-cli releases -o biscuitech -p biscuitech deploys $SENTRY_RELEASE new --env production
